# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/ATM.cache/wt} [current_project]
set_property parent.project_path {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/ATM.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/ATM.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BancnotesNeeded.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BancnotesVerifier.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BlocDisplay.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BlocEliberareNumerar.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BlocRetragereExacta.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BlocRetragereRapida.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BlocSchimbarePin.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/BlocVerificarePin.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/CommandUnit.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/Comparator16bit.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/CounterModulo4.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/Debouncer.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/DigitReader.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/Dmux21_2bits.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/MagazieBancnote.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/MoneyMemory.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/PinMemory.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/SumToBeExtracted.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/atm.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/bcd_adder.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/bcd_adder_digit.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/bcd_substractor.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/bcd_substractor_2digits.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/bcd_substractor_digit.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/comparator1000.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/countermodulo10.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/freqdivider.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/segment7.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/sumcomparator.vhd}
  {D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/ATM/Interface.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Stefan/UTCN/An 1 Sem 2/DSD/Proiect_ATM/final/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Interface -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Interface.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Interface_utilization_synth.rpt -pb Interface_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
